name: Deploy to Digital Ocean Droplet

on:
  push:
    branches:
      - main # or any branch you want to deploy from

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install pnpm
        run: |
          npm install -g pnpm

      - name: Install Dependencies and Build
        run: |
          pnpm install
          pnpm run build

      - name: Archive Dist Folder
        run: |
          tar -czvf dist.tar.gz ./dist ./prisma package.json pnpm-lock.yaml

      - name: Copy Dist Archive to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: 'dist.tar.gz'
          target: '/root/kantt-api'

      - name: Deploy on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export PATH="/root/.nvm/versions/node/v18.19.0/bin:$PATH"
            tar -xzvf /root/kantt-api/dist.tar.gz -C /root/kantt-api
            cd /root/kantt-api
            pnpm install --prod
            pnpm db:generate
            pm2 start /root/kantt-api/dist/main.js -f
